package Model;
// Generated Apr 6, 2019 6:14:55 PM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Integer PId;
     private String size;
     private int quantity;
     private String color;
     private int userId;

    public Orders() {
    }

	
    public Orders(int quantity, int userId) {
        this.quantity = quantity;
        this.userId = userId;
    }
    public Orders(Integer PId, String size, int quantity, String color, int userId) {
       this.PId = PId;
       this.size = size;
       this.quantity = quantity;
       this.color = color;
       this.userId = userId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPId() {
        return this.PId;
    }
    
    public void setPId(Integer PId) {
        this.PId = PId;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }




}


