package Model;
// Generated Apr 6, 2019 6:14:55 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String mobileNo;
     private String email;
     private String address1;
     private String address2;
     private String city;
     private Integer postCode;
     private String country;
     private String province;
     private String password;

    public Users() {
    }

    public Users(String firstName, String lastName, String mobileNo, String email, String address1, String address2, String city, Integer postCode, String country, String province, String password) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.mobileNo = mobileNo;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.postCode = postCode;
       this.country = country;
       this.province = province;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(Integer postCode) {
        this.postCode = postCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


